apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-log
spec:
  integration:
    traits:
      service-binding:
        configuration:
          serviceBindings:
          - rhoas.redhat.com/v1alpha1:KafkaConnection:test
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: managed-kafka-source
    properties:
      topic: test
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink